dist: trusty
sudo: required
services:
  - docker
language: go
go:
- 1.9.1

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
- sudo sed 's/DOCKER_OPTS="/DOCKER_OPTS="--insecure-registry=localhost:5000 /g' -i /etc/default/docker
- sudo cat /etc/default/docker
- sudo service docker restart
- export DOCKER_REGISTRY_ADDRESS="localhost:5000" DOCKER_REGISTRY_USER="testuser" DOCKER_REGISTRY_PASS="testpwd" DOCKER_PRIVATE_IMAGE="localhost:5000/my-private-service"
- bash scripts/testing/setup_private_registry.sh

script:
- make test
- make testacc
- make vendor-status
- make vet

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
